gusindra/hireach

resources/views/livewire/audience/profile.blade.php
resources/views/livewire/contact/delete.blade.php
resources/views/livewire/contact/profile.blade.php
resources/views/resource/show-audience.blade.php

update bug contact show and add menu in audience

fix error contact and audience

---

resources/views/livewire/audience/profile.blade.php
resources/views/livewire/contact/delete.blade.php
resources/views/livewire/contact/profile.blade.php
resources/views/menu/user-content.blade.php
resources/views/resource/show-audience.blade.php

Development: update contact resource

---

routes/web.php

fix error route list

---

resources/views/welcome.blade.php

update landing page website

---

storage/api-docs/api-v2.yaml

update url api server live

---

app/Http/Controllers/ApiOneWayController.php
app/Jobs/ProcessSmsApi.php
app/Jobs/ProcessWaApi.php
app/Observers/SmsBlastObserver.php

update Longnumber API

---

app/Console/Commands/CheckProviderEmail.php
app/Console/Commands/CheckProviderWA.php
app/Http/Controllers/ApiOneWayController.php
app/Http/Controllers/ApiRequestController.php
app/Jobs/ProcessCallBackStatus.php
app/Jobs/ProcessSmsApi.php
app/Jobs/ProcessWaApi.php
routes/api.php

- add new callback provider job
- update new route for contect em callback url

Dev new callback provider

---

app/Exports/ExportWeTalkContact.php
app/Http/Controllers/ApiOneWayController.php
app/Http/Controllers/CampaignController.php
app/Http/Livewire/Campaign/Add.php
app/Http/Livewire/Campaign/Edit.php
app/Http/Livewire/Commercial/Progress.php
app/Http/Livewire/Resource/AddResource.php
app/Http/Livewire/Table/CampaignTable.php
app/Http/Resources/CampaignResource.php
app/Jobs/ProcessCampaignApi.php
app/Jobs/ProcessEmailApi.php
app/Jobs/ProcessSmsApi.php
app/Jobs/ProcessWaApi.php
app/Models/Campaign.php
app/Observers/QuotationObserver.php
app/Observers/SmsBlastObserver.php
database/migrations/2022_09_19_055053_create_operator_phone_number_table.php
database/seeders/OperatorPhoneNumberSeeder.php
resources/views/assistant/commercial/quotation/show.blade.php
resources/views/livewire/campaign/edit.blade.php
resources/views/livewire/commercial/progress.blade.php
resources/views/livewire/contact/export.blade.php
resources/views/payment/show-quotation.blade.php
storage/api-docs/api-local.yaml
storage/api-docs/api-production.yaml

update provider3 WT v1.0 not include hit API Create Campaign & Start Campaign

Dev provider3 wt

---

app/Http/Livewire/DeleteNotification.php
app/Http/Livewire/Order/Add.php
app/Http/Livewire/Resource/AddResource.php
app/Http/Livewire/Saldo/TopupUser.php
app/Http/Livewire/Table/NotificationTable.php
app/Observers/OrderProductObserver.php
database/seeders/TeamsUserTableSeeder.php
resources/views/livewire/switch-team.blade.php
resources/views/tables/delete-notification.blade.php
tests/Feature/NotificationTest.php
tests/Feature/OrderAdminTest.php
tests/Feature/QuotationAdminTest.php

Task Fixed
===================================================================
Tests\Feature\NotificationTest > it deletes the notification
Tests\Feature\OrderAdminTest > can update commission agent
===================================================================
Tests\Feature\OrderTopupUserTest > topup 1 auto
Tests\Feature\OrderTopupUserTest > topup 2 auto
===================================================================
Fixed Bug Perhitungan [comment  create TAX  in Top Up User]
===================================================================
Fixed Eror Data Invoice Admin if created  by Admin
===================================================================
Membuat seeder untu Team User
===================================================================
Memberbaiki Delete …

bug order admin side and testing update

---

app/Actions/CheckApiResponse.php
app/Console/Commands/CheckProviderSMS.php
app/Http/Controllers/ApiRequestController.php
app/Http/Controllers/ApiTwoWayController.php
app/Http/Livewire/Order/Add.php
app/Http/Livewire/Resource/AddResource.php
app/Http/Livewire/Setting/Add.php
app/Http/Livewire/Setting/Edit.php
app/Http/Livewire/User/AddProvider.php
app/Jobs/ProcessInboundMessage.php
app/Jobs/ProcessSmsApi.php
app/Jobs/ProcessSmsStatus.php
app/Models/ProviderUser.php
app/Models/Request.php
app/Observers/OrderObserver.php
database/migrations/2024_07_18_122530_add_field_from_to_provider_user.php
resources/views/livewire/provider/add-setting-provider.blade.php
resources/views/livewire/setting/add.blade.php
resources/views/livewire/setting/company-add.blade.php
resources/views/livewire/setting/edit.blade.php
resources/views/livewire/setting/general/commerce-item/add.blade.php
resources/views/livewire/setting/general/product-line/add.blade.php
resources/views/livewire/user/add-provider.blade.php
resources/views/settings/company/companies.blade.php
routes/api.php
tests/Feature/SendResourceUserTest.php

- add job mo message sms
- add url mo message sms
- update url dn message sms
- test local mk sms firmapps

Dev implement mk sms

---

app/Http/Controllers/CommercialController.php
app/Http/Controllers/InvoiceController.php
app/Http/Controllers/OrderController.php
app/Http/Livewire/Order/Edit.php
app/Http/Livewire/Order/Item.php
app/Http/Livewire/Order/OrderProgress.php
app/Http/Livewire/Payment/Transfer.php
app/Observers/OrderObserver.php
resources/views/assistant/order/show-order-user.blade.php
resources/views/assistant/order/template.blade.php
resources/views/livewire/order/edit.blade.php
resources/views/livewire/payment/history.blade.php
resources/views/livewire/payment/transfer.blade.php

🐞 fix: fix bug calculation order admin
🔵 other: make submit order reactive
✨feature: change select client order admin to search

Update Improve Order Admin 

---

app/Actions/Fortify/CreateNewUser.php
app/Actions/Jetstream/AddTeamMember.php
app/Http/Controllers/DashboardController.php
app/Http/Controllers/TeamInvitationController.php
app/Http/Livewire/Role/Member.php
app/Http/Livewire/SwitchTeam.php
app/Http/Livewire/Team/InviteTeamMemberForm.php
app/Models/User.php
resources/views/components/switchable-team.blade.php
resources/views/layouts/app.blade.php
resources/views/livewire/role/member.blade.php
resources/views/livewire/switch-team.blade.php
resources/views/livewire/team/chat.blade.php
resources/views/livewire/team/invite-team-member-form.blade.php
resources/views/livewire/teams/invite-team-member-form.blade.php
resources/views/navigation-menu.blade.php
resources/views/teams/show.blade.php
resources/views/teams/team-member-manager.blade.php
resources/views/teams/update-team-name-form.blade.php
resources/views/vendor/jetstream/components/banner.blade.php
routes/web.php

✨feature: add invitation teams by link

Update Invitation To Link

---

app/Helpers/Helper.php
app/Http/Controllers/SettingController.php
app/Http/Livewire/Campaign/Edit.php
app/Http/Livewire/Role/Member.php
app/Http/Livewire/Setting/Notification/Add.php
app/Http/Livewire/Table/NotificationTable.php
app/Http/Livewire/Team/Chat.php
resources/views/label/label.blade.php
resources/views/layouts/app.blade.php
resources/views/livewire/order/edit.blade.php
resources/views/livewire/role/member.blade.php
resources/views/livewire/team/chat.blade.php
resources/views/teams/team-member-manager.blade.php
tests/Feature/RoleAdminTest.php

🐞 fix: role permissions typo
🐞 fix: fix delete or remove user from role

✨feature: Delete and view notice update table

---

app/Http/Controllers/UserController.php
app/Http/Livewire/Table/DepartmentTable.php
resources/views/menu/admin-menu-user.blade.php
resources/views/user/department.blade.php
routes/web.php

✨feature: add manual department in admin panel

---

app/Http/Controllers/ApiViGuardController.php
app/Http/Livewire/Contact/Department.php
composer.json
composer.lock
config/filesystems.php
resources/views/livewire/contact/department.blade.php
resources/views/user/department.blade.php
routes/web.php

Setup connection to sftp & ftp server

Dev sftp configuration

---

app/Http/Controllers/UserController.php
app/Http/Livewire/Contact/Search.php
app/Http/Livewire/Department/SettingContact.php
app/Http/Livewire/Department/Update.php
app/Http/Livewire/Table/DepartmentTable.php
app/Http/Livewire/Table/DepartmentUserTable.php
app/Models/Department.php
config/viguard.php
database/migrations/2024_09_13_164011_add_server_to_department.php
resources/views/layouts/app.blade.php
resources/views/livewire/department/search.blade.php
resources/views/livewire/department/update.blade.php
resources/views/livewire/user/client.blade.php
resources/views/menu/admin-menu-user-profile.blade.php
resources/views/navigation-menu.blade.php
resources/views/user/client-to-user.blade.php
resources/views/user/department.blade.php
resources/views/user/user-depart-client.blade.php
resources/views/user/user-depart.blade.php
resources/views/user/user-request.blade.php
resources/views/vendor/jetstream/components/authentication-card-logo.blade.php
resources/views/welcome.blade.php
routes/api.php
routes/web.php

department change for user ViGuard
- set department client contact
- update department from server config viguard

Dev dept user admin

---

app/Http/Livewire/Setting/General/CommerceItem/Add.php
config/menu.php
resources/views/api/index.blade.php
resources/views/components/input-helper.blade.php
resources/views/livewire/datatables/datatable.blade.php
resources/views/livewire/datatables/header-no-hide.blade.php
resources/views/livewire/setting/general/commerce-item/add.blade.php
resources/views/livewire/user/add-provider.blade.php
resources/views/menu/user-setting.blade.php
resources/views/navigation-menu.blade.php
resources/views/vendor/jetstream/components/action-section.blade.php
resources/views/vendor/jetstream/components/input-helper.blade.php

update last revision error from production

Dev revision menu structure to Dev

---

app/Http/Livewire/Department/Update.php
app/Http/Livewire/Provider/Edit.php
app/Http/Livewire/Setting/General/CommerceItem/Edit.php
app/Http/Livewire/User/Client.php
app/Models/CommerceItem.php
app/Models/OperatorPhoneNumber.php
database/migrations/2024_10_14_142619_add_operator_id_to_commerce_items_table.php
resources/views/livewire/provider/edit.blade.php
resources/views/livewire/setting/general/commerce-item/edit.blade.php
resources/views/livewire/user/client.blade.php
resources/views/provider/provider-detail.blade.php

Relasi Commerce item ke provider
menambahkan migrasi untuk operator_id -> operator_phone_number
Validasi saat setting ga ada yang cocok saat update departement 
Side menu view provider disesuaikan 
ubah channel di provider mendjadi sku valuenya

🔵 other: add operator id  field to commerce item

---

app/Http/Controllers/DashboardController.php
app/Http/Livewire/Provider/Add.php
app/Http/Livewire/Provider/Edit.php
app/Http/Livewire/Saldo/Topup.php
app/Http/Livewire/Setting/CompanyEdit.php
app/Http/Livewire/Setting/General/CommerceItem/Edit.php
app/Http/Livewire/Setting/Notification/Add.php
app/Models/Provider.php
app/Models/SaldoUser.php
config/menu.php
database/migrations/2024_10_15_143213_add_type_to_providers_table.php
resources/views/dashboard-consumption-summary.blade.php
resources/views/dashboard/consumption-summary.blade.php
resources/views/dashboard/provider-summary.blade.php
resources/views/livewire/order/edit.blade.php
resources/views/livewire/provider/add.blade.php
resources/views/livewire/provider/edit.blade.php
resources/views/livewire/saldo/topup.blade.php
resources/views/livewire/user/add.blade.php
routes/web.php

- Create notification Error Auth 
- Redirect Delete Company malah return array kosong
- Redirect Delete Commerce Item malah return array kosong 
- Tombol Create yang user masih salah , masih pake tombol create admin
- Show order yang Unpaid / Paid masih bisa search cust nya tapi ga bisa di simpan 
- Add SaldoUser di provider
- Summary Provider 
- Summary Consumption
- Migrasi menambahkan field type di provider

✨feature: Dashboard Summary

---

app/Http/Controllers/ApiResourceController.php
app/Http/Livewire/ValidationResource/AddContact.php
app/Http/Livewire/ValidationResource/AddValidation.php
database/seeders/BillingUsersTableSeeder.php
database/seeders/CompaniesTableSeeder.php
database/seeders/DatabaseSeeder.php
database/seeders/ProviderTableSeeder.php
database/seeders/ProviderUserSeeder.php
tests/Feature/ApiClientValidationTest.php
tests/Feature/ContactResourceValidationTest.php

fixed test
api skiptrace
api validation
render order user
render form top up
render order user

🐞 fix: fix error test

---

app/Http/Controllers/OrderController.php
app/Http/Livewire/Order/Add.php
app/Http/Livewire/Saldo/Billing.php
app/Http/Livewire/User/Add.php
app/Http/Livewire/User/Profile.php
app/Observers/CommerceItemObserver.php
config/menu.php
resources/views/livewire/order/add.blade.php
resources/views/livewire/saldo/billing.blade.php
resources/views/livewire/user/add.blade.php
resources/views/user/user-profile.blade.php
resources/views/user/user-table.blade.php

- Balance (postpaid) dimunculkan sebagai tagihan 
- Fix update SKU (Update Provider dan Provider User)
- Hapus menu TRacing data di menu setting
- Topup melalui admin, Hapus type selain topup , default topup
- Menu Order :
- Prepaid [Table Order]
- Post Paid [Table Billing]

🐞 fix: fix admin side

---

config/menu.php
resources/views/menu/user-balance.blade.php
resources/views/menu/user-content.blade.php
resources/views/menu/user-dashboard.blade.php
resources/views/menu/user-engagement.blade.php
resources/views/navigation-menu.blade.php

🔵 other: Show balance only for prepaid users
🔵 other: Hide balance in the logout popup for users.
🔵 other: Disable 'Create Team' option for users.
🔵 other: Migrate all user menu items to the config menu."

✨ Update user side
